import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import GlobalTheme from './globalTheme';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalTheme>
          <NavBar />
          <main className='p-5'>
            {children}
          </main>
        </GlobalTheme>
      </body>
    </html>
  )
}
