import QueryClientProvider from "@/QueryClientProvider";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import AuthProvider from "./auth/Provider";
import GlobalTheme from './globalTheme';
import './globals.css';
config.autoAddCss = false;


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <AuthProvider>
            <GlobalTheme>
              <NavBar />
              <main className='p-5'>
                <div className="max-w-7xl">
                  {children}
                </div>
              </main>
            </GlobalTheme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
